//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employe
    {
        public Employe()
        {
            this.EmployeProjets = new HashSet<EmployeProjet>();
        }
    
        public int NoEmploye { get; set; }
        public string Prenom { get; set; }
        public string Nom { get; set; }
        public string Telephone { get; set; }
        public string Courriel { get; set; }
    
        public virtual ICollection<EmployeProjet> EmployeProjets { get; set; }
    }
}
