//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeProjet
    {
        public string NoProjet { get; set; }
        public int NoEmploye { get; set; }
        public System.DateTime DateAssignee { get; set; }
        public System.DateTime DateRemise { get; set; }
    
        public virtual Employe Employe { get; set; }
        public virtual Projet Projet { get; set; }
    }
}
