//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameWork
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmployeProjetEntities : DbContext
    {
        public EmployeProjetEntities()
            : base("name=EmployeProjetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Employe> Employes { get; set; }
        public DbSet<EmployeProjet> EmployeProjets { get; set; }
        public DbSet<Projet> Projets { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
