//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projet
    {
        public Projet()
        {
            this.EmployeProjets = new HashSet<EmployeProjet>();
        }
    
        public string NoProjet { get; set; }
        public string TitreProjet { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
    
        public virtual ICollection<EmployeProjet> EmployeProjets { get; set; }
    }
}
